#version 450

#include "push_constant.glsl"
#include "../common/tonemapping.glsl"

layout(set = 0, binding = 0, rgba32f) uniform readonly image2D HdrColor;
layout(set = 0, binding = 1, rgba32f) uniform writeonly image2D Color;

void main() {
  vec4 color = imageLoad(HdrColor, ivec2(gl_GlobalInvocationID.xy));

  color.rgb = sapienToneMap(color.rgb, exposure, toneMapper);
  color.a = clamp(color.a, 0.0, 1.0);

  imageStore(Color, ivec2(gl_GlobalInvocationID.xy), color);
}
