from __future__ import annotations
import numpy
import pybind11_stubgen.typing_ext
import sapien.pysapien
import sapien.pysapien.internal_renderer
import sapien.pysapien.physx
import typing
__all__ = ['RenderBodyComponent', 'RenderCameraComponent', 'RenderCameraGroup', 'RenderCubemap', 'RenderCudaMeshComponent', 'RenderDirectionalLightComponent', 'RenderLightComponent', 'RenderMaterial', 'RenderParallelogramLightComponent', 'RenderPointCloudComponent', 'RenderPointLightComponent', 'RenderSceneLoaderNode', 'RenderShape', 'RenderShapeBox', 'RenderShapeCapsule', 'RenderShapeCylinder', 'RenderShapePlane', 'RenderShapePrimitive', 'RenderShapeSphere', 'RenderShapeTriangleMesh', 'RenderShapeTriangleMeshPart', 'RenderSpotLightComponent', 'RenderSystem', 'RenderSystemGroup', 'RenderTexture', 'RenderTexture2D', 'RenderTexturedLightComponent', 'RenderVRDisplay', 'RenderWindow', 'SapienRenderer', 'clear_cache', 'enable_vr', 'get_camera_shader_dir', 'get_device_summary', 'get_imgui_ini_filename', 'get_msaa', 'get_ray_tracing_denoiser', 'get_ray_tracing_dof_aperture', 'get_ray_tracing_dof_plane', 'get_ray_tracing_path_depth', 'get_ray_tracing_samples_per_pixel', 'get_viewer_shader_dir', 'get_vr_action_manifest_filename', 'get_vr_enabled', 'load_scene', 'set_camera_shader_dir', 'set_global_config', 'set_imgui_ini_filename', 'set_light_colors', 'set_light_directions', 'set_light_poses', 'set_log_level', 'set_msaa', 'set_picture_format', 'set_ray_tracing_denoiser', 'set_ray_tracing_dof_aperture', 'set_ray_tracing_dof_plane', 'set_ray_tracing_path_depth', 'set_ray_tracing_samples_per_pixel', 'set_viewer_shader_dir', 'set_vr_action_manifest_filename']
M = typing.TypeVar("M", bound=int)
N = typing.TypeVar("N", bound=int)
class RenderBodyComponent(sapien.pysapien.Component):
    shading_mode: int
    visibility: float
    def __init__(self) -> None:
        ...
    def attach(self, shape: RenderShape) -> RenderBodyComponent:
        ...
    def clone(self) -> RenderBodyComponent:
        ...
    def compute_global_aabb_tight(self) -> numpy.ndarray[tuple[typing.Literal[2], typing.Literal[3]], numpy.dtype[numpy.float32]]:
        ...
    def disable_render_id(self) -> None:
        ...
    def enable_render_id(self) -> None:
        ...
    def get_global_aabb_fast(self) -> numpy.ndarray[tuple[typing.Literal[2], typing.Literal[3]], numpy.dtype[numpy.float32]]:
        ...
    @typing.overload
    def set_property(self, name: str, value: numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]] | list[float] | tuple) -> None:
        ...
    @typing.overload
    def set_property(self, name: str, value: int) -> None:
        ...
    @typing.overload
    def set_property(self, name: str, value: float) -> None:
        ...
    def set_texture(self, name: str, texture: RenderTexture) -> None:
        ...
    def set_texture_array(self, name: str, textures: list[RenderTexture]) -> None:
        ...
    @property
    def _internal_node(self) -> sapien.pysapien.internal_renderer.Node:
        ...
    @property
    def is_render_id_disabled(self) -> bool:
        ...
    @property
    def render_shapes(self) -> list[RenderShape]:
        ...
class RenderCameraComponent(sapien.pysapien.Component):
    far: float
    local_pose: sapien.pysapien.Pose
    near: float
    skew: float
    def __init__(self, width: int, height: int, shader_dir: str = '') -> None:
        ...
    def get_extrinsic_matrix(self) -> numpy.ndarray[tuple[typing.Literal[3], typing.Literal[4]], numpy.dtype[numpy.float32]]:
        """
        Get 3x4 extrinsic camera matrix in OpenCV format.
        """
    def get_far(self) -> float:
        ...
    def get_global_pose(self) -> sapien.pysapien.Pose:
        ...
    def get_height(self) -> int:
        ...
    def get_intrinsic_matrix(self) -> numpy.ndarray[tuple[typing.Literal[3], typing.Literal[3]], numpy.dtype[numpy.float32]]:
        """
        Get 3x3 intrinsic camera matrix in OpenCV format.
        """
    def get_local_pose(self) -> sapien.pysapien.Pose:
        ...
    def get_mode(self) -> typing.Literal['perspective', 'orthographic']:
        ...
    def get_model_matrix(self) -> numpy.ndarray[tuple[typing.Literal[4], typing.Literal[4]], numpy.dtype[numpy.float32]]:
        """
        Get model matrix (inverse of extrinsic matrix) used in rendering (Y up, Z back)
        """
    def get_near(self) -> float:
        ...
    def get_picture(self, name: str) -> numpy.ndarray[typing.Any, numpy.dtype[typing.Any]]:
        ...
    def get_picture_cuda(self, name: str) -> sapien.pysapien.CudaArray:
        """
        This function transfers the rendered image into a CUDA buffer.
        
        Usage:
        
        # use torch backend
        sapien.set_cuda_tensor_backend("torch")  # called once per process
        image: torch.Tensor = camera.get_picture_cuda()
        
        # use default backend
        image = camera.get_picture_cuda()
        torch_tensor = torch.as_tensor(image)
        
        Warning: The camera must not be destroyed when the GPU tensor is in use by the
        consumer library. Make a copy if needed.
        """
    def get_picture_names(self) -> list[str]:
        ...
    def get_projection_matrix(self) -> numpy.ndarray[tuple[typing.Literal[4], typing.Literal[4]], numpy.dtype[numpy.float32]]:
        """
        Get projection matrix in used in rendering (right-handed NDC with [-1,1] XY and [0,1] Z)
        """
    def get_skew(self) -> float:
        ...
    def get_width(self) -> int:
        ...
    def set_far(self, far: float) -> None:
        ...
    def set_focal_lengths(self, fx: float, fy: float) -> None:
        ...
    def set_fovx(self, fov: float, compute_y: bool = True) -> None:
        ...
    def set_fovy(self, fov: float, compute_x: bool = True) -> None:
        ...
    def set_gpu_pose_batch_index(self, index: int) -> None:
        ...
    def set_local_pose(self, pose: sapien.pysapien.Pose) -> None:
        ...
    def set_scenes(self, scenes: list[sapien.pysapien.Scene]) -> None:
        """Select base render scenes; shared scenes are included once without offsets."""
        ...
    def set_near(self, near: float) -> None:
        ...
    @typing.overload
    def set_orthographic_parameters(self, near: float, far: float, top: float) -> None:
        ...
    @typing.overload
    def set_orthographic_parameters(self, near: float, far: float, left: float, right: float, bottom: float, top: float) -> None:
        ...
    def set_perspective_parameters(self, near: float, far: float, fx: float, fy: float, cx: float, cy: float, skew: float) -> None:
        ...
    def set_principal_point(self, cx: float, cy: float) -> None:
        ...
    @typing.overload
    def set_property(self, name: str, value: int) -> None:
        ...
    @typing.overload
    def set_property(self, name: str, value: float) -> None:
        ...
    def set_skew(self, skew: float) -> None:
        ...
    def set_texture(self, name: str, texture: RenderTexture) -> None:
        ...
    def set_texture_array(self, name: str, textures: list[RenderTexture]) -> None:
        ...
    def take_picture(self) -> None:
        ...
    @property
    def _cuda_buffer(self) -> sapien.pysapien.CudaArray:
        """
        Debug only. Get the CUDA buffer containing GPU data for this camera, including transformaion matrices, sizes, and user-defined shader fields.
        """
    @property
    def _internal_renderer(self) -> sapien.pysapien.internal_renderer.Renderer:
        ...
    @property
    def camera_state_version(self) -> int:
        """
        Coarse dirty version of the CPU camera state (projection/intrinsics in every pose mode,
        plus the pose in 'cpu' mode). RenderSystemGroup.update_render() re-uploads camera state
        only when this version moved; an unchanged version means zero per-frame camera uploads.
        """
    @property
    def cx(self) -> float:
        ...
    @property
    def cy(self) -> float:
        ...
    @property
    def fovx(self) -> float:
        ...
    @property
    def fovy(self) -> float:
        ...
    @property
    def fx(self) -> float:
        ...
    @property
    def fy(self) -> float:
        ...
    @property
    def global_pose(self) -> sapien.pysapien.Pose:
        ...
    @property
    def height(self) -> int:
        ...
    @property
    def mode(self) -> typing.Literal['perspective', 'orthographic']:
        ...
    @property
    def pose_mode(self) -> typing.Literal['static', 'cpu', 'cuda']:
        """
        Grouped pose source configured through RenderCameraGroup.set_pose_mode(); 'static' by default.
        """
    @property
    def ortho_bottom(self) -> float:
        ...
    @property
    def ortho_left(self) -> float:
        ...
    @property
    def ortho_right(self) -> float:
        ...
    @property
    def ortho_top(self) -> float:
        ...
    @property
    def width(self) -> int:
        ...
class RenderCameraGroup:
    def get_cuda_pose_index(self, camera: RenderCameraComponent) -> int:
        """
        Row index of a cuda-mode camera in cuda_poses. Raises for mounted cameras (their pose derives
        from the GPU parent) and for cameras with pose mode 'static' or 'cpu'.
        """
    def get_picture_cuda(self, name: str) -> sapien.pysapien.CudaArray:
        ...
    def set_cuda_pose(self, camera: RenderCameraComponent, pose: sapien.pysapien.Pose) -> None:
        """
        Copy one CPU-authored world pose into a cuda-mode camera's CUDA pose row on the camera group's
        configured CUDA stream. This synchronous convenience call is ordered with transform updates
        on that stream; the pose takes effect at the next update_render().
        """
    def set_pose_mode(self, camera: RenderCameraComponent, mode: typing.Literal['static', 'cpu', 'cuda']) -> None:
        """
        Configure a member camera's pose source before RenderSystemGroup.gpu_init():
        'static' (default): the pose is a one-time snapshot at gpu_init(); CPU pose setters raise.
        'cpu': the CPU pose stays authoritative; set_local_pose()/entity pose changes upload at the
        next update_render().
        'cuda': the camera receives a group-owned CUDA pose row [px, py, pz, qw, qx, qy, qz]
        (cuda_poses / set_cuda_pose); CPU pose setters raise.
        Cameras mounted on PhysX GPU bodies are automatically CUDA-attached (they follow the parent
        pose row without a group row) and cannot be configured 'cpu' or 'static'.
        Projection/intrinsics stay CPU real-time in every mode.
        """
    def take_picture(self) -> None:
        ...
    @property
    def cuda_poses(self) -> sapien.pysapien.CudaArray:
        """
        CUDA buffer of world pose rows [px, py, pz, qw, qx, qy, qz] for the cameras configured with
        pose mode 'cuda'. Rows are seeded once from the CPU pose at gpu_init(); write rows on the GPU
        (or copy explicitly) before update_render(). The buffer only exists when at least one camera
        uses pose mode 'cuda'.
        """
class RenderCubemap:
    @typing.overload
    def __init__(self, filename: str) -> None:
        ...
    @typing.overload
    def __init__(self, px: str, nx: str, py: str, ny: str, pz: str, nz: str) -> None:
        ...
    def export(self, filename: str) -> None:
        ...
    @property
    def _internal_cubemap(self) -> sapien.pysapien.internal_renderer.Cubemap:
        ...
class RenderCudaMeshComponent(sapien.pysapien.Component):
    material: RenderMaterial
    triangle_count: int
    vertex_count: int
    def __init__(self, max_vertex_count: int, max_triangle_count: int) -> None:
        ...
    def get_cuda_triangles(self) -> sapien.pysapien.CudaArray:
        ...
    def get_cuda_vertices(self) -> sapien.pysapien.CudaArray:
        ...
    def get_material(self) -> RenderMaterial:
        ...
    def get_triangle_count(self) -> int:
        ...
    def get_vertex_count(self) -> int:
        ...
    def notify_vertex_updated(self, cuda_stream: int = 0) -> None:
        ...
    def set_material(self, material: RenderMaterial) -> None:
        ...
    def set_triangle_count(self, count: int) -> None:
        ...
    def set_triangles(self, triangles: numpy.ndarray[numpy.uint32[M, 3]]) -> None:
        ...
    def set_vertex_count(self, count: int) -> None:
        ...
    @property
    def cuda_triangles(self) -> sapien.pysapien.CudaArray:
        ...
    @property
    def cuda_vertices(self) -> sapien.pysapien.CudaArray:
        ...
class RenderDirectionalLightComponent(RenderLightComponent):
    shadow_half_size: float
    def __init__(self) -> None:
        ...
    def get_shadow_half_size(self) -> float:
        ...
    def set_shadow_half_size(self, size: float) -> None:
        ...
class RenderLightComponent(sapien.pysapien.Component):
    color: numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]]
    local_pose: sapien.pysapien.Pose
    pose_mode: typing.Literal['static', 'cpu']
    shadow: bool
    shadow_far: float
    shadow_map_size: int
    shadow_near: float
    def disable_shadow(self) -> None:
        ...
    def enable_shadow(self) -> None:
        ...
    def get_color(self) -> numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]]:
        ...
    def get_global_pose(self) -> sapien.pysapien.Pose:
        ...
    def get_local_pose(self) -> sapien.pysapien.Pose:
        ...
    def get_shadow_far(self) -> float:
        ...
    def get_shadow_map_size(self) -> int:
        ...
    def get_shadow_near(self) -> float:
        ...
    def get_pose_mode(self) -> typing.Literal['static', 'cpu']:
        ...
    def set_color(self, color: numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]] | list[float] | tuple) -> None:
        ...
    def set_local_pose(self, pose: sapien.pysapien.Pose) -> None:
        ...
    def set_shadow_far(self, far: float) -> None:
        ...
    def set_shadow_map_size(self, size: int) -> None:
        ...
    def set_shadow_near(self, near: float) -> None:
        ...
    def set_pose_mode(self, mode: typing.Literal['static', 'cpu']) -> None:
        """
        Configure the light's grouped pose source before RenderSystemGroup.gpu_init():
        'static' (default): the pose is a one-time snapshot at gpu_init(); changing it raises.
        'cpu': the CPU pose stays authoritative; entity/local pose changes upload at the next
        update_render(). A cpu-mode light must not share its entity with a PhysX GPU body.
        Color, FOV, shape, and shadow near/far/half-size stay CPU real-time in both modes.
        """
    @property
    def global_pose(self) -> sapien.pysapien.Pose:
        ...
class RenderMaterial:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]
    base_color: typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(4)]
    base_color_texture: RenderTexture2D
    diffuse_texture = ...
    emission: typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(4)]
    emission_texture: RenderTexture2D
    ior: float
    metallic: float
    metallic_texture: RenderTexture2D
    normal_texture: RenderTexture2D
    roughness: float
    roughness_texture: RenderTexture2D
    specular: float
    transmission: float
    transmission_roughness: float
    transmission_texture: RenderTexture2D
    def __eq__(self, arg0: RenderMaterial) -> bool:  # type: ignore[override]
        ...
    def __init__(self, emission: typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(4)] = [0.0, 0.0, 0.0, 0.0], base_color: typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(4)] = [1.0, 1.0, 1.0, 1.0], specular: float = 0.5, roughness: float = 0.44999998807907104, metallic: float = 0.0, transmission: float = 0.0, ior: float = 1.4500000476837158, transmission_roughness: float = 0.0) -> None:
        ...
    def get_base_color(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(4)]:
        ...
    def get_base_color_texture(self) -> RenderTexture2D:
        ...
    def get_diffuse_texture(self):
        ...
    def get_emission(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(4)]:
        ...
    def get_emission_texture(self) -> RenderTexture2D:
        ...
    def get_ior(self) -> float:
        ...
    def get_metallic(self) -> float:
        ...
    def get_metallic_texture(self) -> RenderTexture2D:
        ...
    def get_normal_texture(self) -> RenderTexture2D:
        ...
    def get_roughness(self) -> float:
        ...
    def get_roughness_texture(self) -> RenderTexture2D:
        ...
    def get_specular(self) -> float:
        ...
    def get_transmission(self) -> float:
        ...
    def get_transmission_roughness(self) -> float:
        ...
    def get_transmission_texture(self) -> RenderTexture2D:
        ...
    def set_base_color(self, color: typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(4)]) -> None:
        ...
    def set_base_color_texture(self, texture: RenderTexture2D) -> None:
        ...
    def set_diffuse_texture(self, texture):
        ...
    def set_emission(self, emission: typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(4)]) -> None:
        ...
    def set_emission_texture(self, texture: RenderTexture2D) -> None:
        ...
    def set_ior(self, ior: float) -> None:
        ...
    def set_metallic(self, metallic: float) -> None:
        ...
    def set_metallic_texture(self, texture: RenderTexture2D) -> None:
        ...
    def set_normal_texture(self, texture: RenderTexture2D) -> None:
        ...
    def set_roughness(self, roughness: float) -> None:
        ...
    def set_roughness_texture(self, texture: RenderTexture2D) -> None:
        ...
    def set_specular(self, specular: float) -> None:
        ...
    def set_transmission(self, transmission: float) -> None:
        ...
    def set_transmission_roughness(self, roughness: float) -> None:
        ...
    def set_transmission_texture(self, texture: RenderTexture2D) -> None:
        ...
class RenderParallelogramLightComponent(RenderLightComponent):
    def __init__(self) -> None:
        ...
    def get_angle(self) -> float:
        ...
    def get_half_height(self) -> float:
        ...
    def get_half_width(self) -> float:
        ...
    def set_shape(self, half_width: float, half_height: float, angle: float = 1.5707963705062866) -> None:
        ...
    @property
    def angle(self) -> float:
        ...
    @property
    def half_height(self) -> float:
        ...
    @property
    def half_width(self) -> float:
        ...
class RenderPointCloudComponent(sapien.pysapien.Component):
    def __init__(self, capacity: int = 0) -> None:
        ...
    def get_cuda_aabb(self) -> sapien.pysapien.CudaArray | None:
        """
        this function is a temporary hack to help update the AABBs used for ray tracing BLAS. returns None if ray tracing has not been initialized
        """
    def get_cuda_vertices(self) -> sapien.pysapien.CudaArray:
        ...
    def get_vertices(self) -> numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]]:
        """
        Get previously set vertices. This function does not reflect any changes directly made to the GPU.
        """
    def set_attribute(self, name: str, attribute: numpy.ndarray[tuple[M, N], numpy.dtype[numpy.float32]] | list | tuple) -> RenderPointCloudComponent:
        ...
    def set_vertices(self, vertices: numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]] | list | tuple) -> RenderPointCloudComponent:
        ...
class RenderPointLightComponent(RenderLightComponent):
    def __init__(self) -> None:
        ...
class RenderSceneLoaderNode:
    def flatten(self) -> tuple[list[RenderShapeTriangleMesh], list[RenderLightComponent]]:
        ...
    @property
    def children(self) -> list[RenderSceneLoaderNode]:
        ...
    @property
    def light(self) -> RenderLightComponent:
        ...
    @property
    def mesh(self) -> RenderShapeTriangleMesh:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def pose(self) -> sapien.pysapien.Pose:
        ...
    @property
    def scale(self) -> numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]]:
        ...
class RenderShape:
    front_face: typing.Literal['counterclockwise', 'clockwise']
    local_pose: sapien.pysapien.Pose
    name: str
    def clone(self) -> RenderShape:
        ...
    def get_front_face(self) -> typing.Literal['counterclockwise', 'clockwise']:
        ...
    def get_local_pose(self) -> sapien.pysapien.Pose:
        ...
    def get_material(self) -> RenderMaterial:
        ...
    def get_name(self) -> str:
        ...
    def get_parts(self) -> list[RenderShapeTriangleMeshPart]:
        ...
    def get_per_scene_id(self) -> int:
        ...
    def set_front_face(self, front_face: typing.Literal['counterclockwise', 'clockwise']) -> None:
        ...
    def set_gpu_pose_batch_index(self, index: int) -> None:
        ...
    def set_local_pose(self, pose: sapien.pysapien.Pose) -> None:
        ...
    def set_name(self, name: str) -> None:
        ...
    @property
    def material(self) -> RenderMaterial:
        ...
    @property
    def parts(self) -> list[RenderShapeTriangleMeshPart]:
        ...
    @property
    def per_scene_id(self) -> int:
        ...
class RenderShapeBox(RenderShapePrimitive):
    def __init__(self, half_size: numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]] | list[float] | tuple, material: RenderMaterial) -> None:
        ...
    def get_half_size(self) -> numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]]:
        ...
    @property
    def half_size(self) -> numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]]:
        ...
class RenderShapeCapsule(RenderShapePrimitive):
    def __init__(self, radius: float, half_length: float, material: RenderMaterial) -> None:
        ...
    def get_half_length(self) -> float:
        ...
    def get_radius(self) -> float:
        ...
    @property
    def half_length(self) -> float:
        ...
    @property
    def radius(self) -> float:
        ...
class RenderShapeCylinder(RenderShapePrimitive):
    def __init__(self, radius: float, half_length: float, material: RenderMaterial) -> None:
        ...
    def get_half_length(self) -> float:
        ...
    def get_radius(self) -> float:
        ...
    @property
    def half_length(self) -> float:
        ...
    @property
    def radius(self) -> float:
        ...
class RenderShapePlane(RenderShapePrimitive):
    def __init__(self, scale: numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]] | list[float] | tuple, material: RenderMaterial) -> None:
        ...
    def get_scale(self) -> numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]]:
        ...
    @property
    def scale(self) -> numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]]:
        ...
class RenderShapePrimitive(RenderShape):
    def get_triangles(self) -> numpy.ndarray[numpy.uint32[M, 3]]:
        ...
    def get_vertex_normal(self) -> numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]]:
        ...
    def get_vertex_uv(self) -> numpy.ndarray[tuple[M, typing.Literal[2]], numpy.dtype[numpy.float32]]:
        ...
    def get_vertices(self) -> numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]]:
        ...
    @property
    def triangles(self) -> numpy.ndarray[numpy.uint32[M, 3]]:
        ...
    @property
    def vertex_normal(self) -> numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]]:
        ...
    @property
    def vertex_uv(self) -> numpy.ndarray[tuple[M, typing.Literal[2]], numpy.dtype[numpy.float32]]:
        ...
    @property
    def vertices(self) -> numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]]:
        ...
class RenderShapeSphere(RenderShapePrimitive):
    def __init__(self, radius: float, material: RenderMaterial) -> None:
        ...
    def get_radius(self) -> float:
        ...
    @property
    def radius(self) -> float:
        ...
class RenderShapeTriangleMesh(RenderShape):
    scale: numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]]
    @typing.overload
    def __init__(self, vertices: numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]] | list | tuple, triangles: numpy.ndarray[numpy.uint32[M, 3]], normals: numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]] | list | tuple, uvs: numpy.ndarray[tuple[M, typing.Literal[2]], numpy.dtype[numpy.float32]] | list | tuple, material: RenderMaterial) -> None:
        ...
    @typing.overload
    def __init__(self, filename: str, scale: numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]] | list[float] | tuple = ..., material: RenderMaterial | None = None) -> None:
        ...
    def get_filename(self) -> str:
        ...
    def get_scale(self) -> numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]]:
        ...
    def set_scale(self, scale: numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]] | list[float] | tuple) -> None:
        """
        Note: this function only works when the shape is not added to scene
        """
    @property
    def filename(self) -> str:
        ...
class RenderShapeTriangleMeshPart:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]
    def __eq__(self, arg0: RenderShapeTriangleMeshPart) -> bool:  # type: ignore[override]
        ...
    def get_cuda_triangles(self) -> sapien.pysapien.CudaArray:
        ...
    def get_cuda_vertices(self) -> sapien.pysapien.CudaArray:
        ...
    def get_material(self) -> RenderMaterial:
        ...
    def get_triangles(self) -> numpy.ndarray[numpy.uint32[M, 3]]:
        ...
    def get_vertex_normal(self) -> numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]]:
        ...
    def get_vertex_uv(self) -> numpy.ndarray[tuple[M, typing.Literal[2]], numpy.dtype[numpy.float32]]:
        ...
    def get_vertices(self) -> numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]]:
        ...
    def set_vertex_normal(self, normal: numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]] | list | tuple) -> None:
        ...
    def set_vertex_uv(self, uv: numpy.ndarray[tuple[M, typing.Literal[2]], numpy.dtype[numpy.float32]] | list | tuple) -> None:
        ...
    @property
    def cuda_triangles(self) -> sapien.pysapien.CudaArray:
        ...
    @property
    def cuda_vertices(self) -> sapien.pysapien.CudaArray:
        ...
    @property
    def material(self) -> RenderMaterial:
        ...
    @property
    def triangles(self) -> numpy.ndarray[numpy.uint32[M, 3]]:
        ...
    @property
    def vertices(self) -> numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]]:
        ...
class RenderSpotLightComponent(RenderLightComponent):
    inner_fov: float
    outer_fov: float
    def __init__(self) -> None:
        ...
    def get_inner_fov(self) -> float:
        ...
    def get_outer_fov(self) -> float:
        ...
    def set_inner_fov(self, fov: float) -> None:
        ...
    def set_outer_fov(self, fov: float) -> None:
        ...
class RenderSystem(sapien.pysapien.System):
    ambient_light: numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]]
    batched_render_shared: bool
    cubemap: RenderCubemap
    @typing.overload
    def __init__(self, device: sapien.pysapien.Device | None = None) -> None:
        ...
    @typing.overload
    def __init__(self, device: str) -> None:
        ...
    def get_ambient_light(self) -> numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]]:
        ...
    def get_batched_render_shared(self) -> bool:
        ...
    def get_cameras(self) -> list[RenderCameraComponent]:
        ...
    def get_cubemap(self) -> RenderCubemap:
        ...
    def get_lights(self) -> list[RenderLightComponent]:
        ...
    def get_point_clouds(self) -> list[RenderPointCloudComponent]:
        ...
    def get_render_bodies(self) -> list[RenderBodyComponent]:
        ...
    def set_ambient_light(self, color: numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]] | list[float] | tuple) -> None:
        ...
    def set_batched_render_shared(self, shared: bool) -> None:
        ...
    def set_cubemap(self, cubemap: RenderCubemap) -> None:
        ...
    @property
    def _internal_scene(self) -> sapien.pysapien.internal_renderer.Scene:
        ...
    @property
    def cameras(self) -> list[RenderCameraComponent]:
        ...
    @property
    def cuda_object_transforms(self) -> sapien.pysapien.CudaArray:
        ...
    @property
    def device(self) -> sapien.pysapien.Device:
        ...
    @property
    def lights(self) -> list[RenderLightComponent]:
        ...
    @property
    def point_clouds(self) -> list[RenderPointCloudComponent]:
        ...
    @property
    def render_bodies(self) -> list[RenderBodyComponent]:
        ...
    @property
    def scene_light_state_version(self) -> int:
        """
        Coarse dirty version of the CPU scene/light state (light properties, cpu-mode light poses,
        ambient light). RenderSystemGroup.update_render() re-uploads light state only when this
        version moved; an unchanged version means zero per-frame light uploads.
        """
class RenderSystemGroup:
    def __init__(self, systems: list[RenderSystem]) -> None:
        ...
    def create_camera_group(self, cameras: list[RenderCameraComponent], picture_names: list[str]) -> RenderCameraGroup:
        ...
    def gpu_init(self) -> None:
        """
        One-time initialization and seal. Resolves final output selections including shared scenes,
        validates their PhysX GPU systems, binds dynamic bodies and mounted cameras, parses camera
        and light pose modes, prepares resources, snapshots static state, seals pose ownership, and
        freezes topology. Configure create_camera_group(), pose modes, and, when GPU objects or
        mounted cameras exist, set_cuda_poses() before calling; afterwards the steady state is
        update_render() plus capture only.
        """
    def set_cuda_poses(self, pose_buffer: sapien.pysapien.CudaArray) -> None:
        ...
    def set_cuda_stream(self, stream: int) -> None:
        ...
    def update_render(self) -> None:
        """
        Per-frame grouped update. It refreshes CPU components (raising if a sealed static pose was
        tampered with), uploads dirty CPU camera state (projection/intrinsics and cpu-mode poses)
        and dirty scene/light state (colors, FOVs, shapes, shadow parameters, ambient, cpu-mode
        light poses), then performs CUDA operations to transfer poses from the buffer provided by
        :func:`set_cuda_poses` into render systems: object transforms plus the view matrices of
        mounted and cuda-mode cameras. With a ray-tracing shader pack, it also updates rigid TLAS
        instances and resets accumulation. When nothing changed on the CPU, no CPU upload is
        performed.
        
        This function waits for any pending CUDA operations on cuda stream provided by :func:`set_cuda_stream`.
        """
class RenderTexture:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]
    def __eq__(self, arg0: RenderTexture) -> bool:  # type: ignore[override]
        ...
    def __init__(self, array: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]] | list | tuple, dim: int, format: str, mipmap_levels: int = 1, filter_mode: typing.Literal['nearest', 'linear'] = 'linear', address_mode: typing.Literal['repeat', 'border', 'edge', 'mirror'] = 'repeat', srgb: bool = False) -> None:
        ...
    def download(self) -> numpy.ndarray[typing.Any, numpy.dtype[typing.Any]]:
        ...
    def get_address_mode(self) -> typing.Literal['repeat', 'border', 'edge', 'mirror']:
        ...
    def get_channels(self) -> int:
        ...
    def get_depth(self) -> int:
        ...
    def get_filter_mode(self) -> typing.Literal['nearest', 'linear']:
        ...
    def get_format(self) -> str:
        ...
    def get_height(self) -> int:
        ...
    def get_mipmap_levels(self) -> int:
        ...
    def get_width(self) -> int:
        ...
    def upload(self, data: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]] | list | tuple) -> None:
        ...
    @property
    def address_mode(self) -> typing.Literal['repeat', 'border', 'edge', 'mirror']:
        ...
    @property
    def channels(self) -> int:
        ...
    @property
    def depth(self) -> int:
        ...
    @property
    def filter_mode(self) -> typing.Literal['nearest', 'linear']:
        ...
    @property
    def format(self) -> str:
        ...
    @property
    def height(self) -> int:
        ...
    @property
    def is_srgb(self) -> bool:
        ...
    @property
    def mipmap_levels(self) -> int:
        ...
    @property
    def width(self) -> int:
        ...
class RenderTexture2D:
    __hash__: typing.ClassVar[None] = None  # type: ignore[assignment]
    def __eq__(self, arg0: RenderTexture2D) -> bool:  # type: ignore[override]
        ...
    @typing.overload
    def __init__(self, array: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]] | list | tuple, format: str, mipmap_levels: int = 1, filter_mode: typing.Literal['nearest', 'linear'] = 'linear', address_mode: typing.Literal['repeat', 'border', 'edge', 'mirror'] = 'repeat', srgb: bool = False) -> None:
        ...
    @typing.overload
    def __init__(self, filename: str, mipmap_levels: int = 1, filter_mode: typing.Literal['nearest', 'linear'] = 'linear', address_mode: typing.Literal['repeat', 'border', 'edge', 'mirror'] = 'repeat', srgb: bool = True) -> None:
        """
        Create texture from file. The srgb parameter only affects files in uint8 format; it should be true for color textures (diffuse, emission) and false for others (normal, roughness)
        """
    def download(self) -> numpy.ndarray[typing.Any, numpy.dtype[typing.Any]]:
        ...
    def get_address_mode(self) -> typing.Literal['repeat', 'border', 'edge', 'mirror']:
        ...
    def get_channels(self) -> int:
        ...
    def get_filename(self) -> str:
        ...
    def get_filter_mode(self) -> typing.Literal['nearest', 'linear']:
        ...
    def get_format(self) -> str:
        ...
    def get_height(self) -> int:
        ...
    def get_mipmap_levels(self) -> int:
        ...
    def get_width(self) -> int:
        ...
    def upload(self, data: numpy.ndarray[typing.Any, numpy.dtype[typing.Any]] | list | tuple) -> None:
        ...
    @property
    def address_mode(self) -> typing.Literal['repeat', 'border', 'edge', 'mirror']:
        ...
    @property
    def channels(self) -> int:
        ...
    @property
    def filename(self) -> str:
        ...
    @property
    def filter_mode(self) -> typing.Literal['nearest', 'linear']:
        ...
    @property
    def format(self) -> str:
        ...
    @property
    def height(self) -> int:
        ...
    @property
    def is_srgb(self) -> bool:
        ...
    @property
    def mipmap_levels(self) -> int:
        ...
    @property
    def width(self) -> int:
        ...
class RenderTexturedLightComponent(RenderSpotLightComponent):
    texture: RenderTexture2D
    def __init__(self) -> None:
        ...
    def get_texture(self) -> RenderTexture2D:
        ...
    def set_texture(self, texture: RenderTexture2D) -> None:
        ...
class RenderVRDisplay:
    root_pose: sapien.pysapien.Pose
    def __init__(self) -> None:
        ...
    def fetch_poses(self) -> None:
        """
        fetches poses of HMD and controllers
        """
    def get_controller_axis_state(self, id: int, axis: int) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(2)]:
        ...
    def get_controller_button_pressed(self, id: int) -> int:
        ...
    def get_controller_button_touched(self, id: int) -> int:
        ...
    def get_controller_ids(self) -> list[int]:
        ...
    def get_controller_pose(self, id: int) -> sapien.pysapien.Pose:
        """
        Gets the local pose of a controller. It should be called immediately after fetch_poses
        """
    def get_hmd_pose(self) -> sapien.pysapien.Pose:
        """
        Gets the local pose of the head set. It should be called immediately after fetch_poses
        """
    def get_left_hand_root_pose(self) -> sapien.pysapien.Pose:
        ...
    def get_left_hand_skeletal_poses(self) -> list[sapien.pysapien.Pose]:
        ...
    def get_right_hand_root_pose(self) -> sapien.pysapien.Pose:
        ...
    def get_right_hand_skeletal_poses(self) -> list[sapien.pysapien.Pose]:
        ...
    def get_root_pose(self) -> sapien.pysapien.Pose:
        ...
    def render(self) -> None:
        ...
    def set_camera_parameters(self, near: float, far: float) -> None:
        ...
    def set_root_pose(self, pose: sapien.pysapien.Pose) -> None:
        ...
    def set_scene(self, scene: sapien.pysapien.Scene) -> None:
        ...
    def update_render(self) -> None:
        """
        update_render implicitly calls fetch_poses to make sure the HMD pose is up-to-date
        """
    @property
    def _internal_scene(self) -> sapien.pysapien.internal_renderer.Scene:
        ...
class RenderWindow:
    cursor: bool
    denoiser: typing.Literal['none', 'oidn', 'optix']
    def __init__(self, width: int, height: int, shader_dir: str) -> None:
        ...
    def get_camera_model_matrix(self) -> numpy.ndarray[tuple[typing.Literal[4], typing.Literal[4]], numpy.dtype[numpy.float32]]:
        ...
    def get_camera_pose(self) -> sapien.pysapien.Pose:
        ...
    def get_camera_position(self) -> numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]]:
        ...
    def get_camera_projection_matrix(self) -> numpy.ndarray[typing.Any, numpy.dtype[numpy.float32]]:
        ...
    def get_camera_property_float(self, key: str) -> float:
        ...
    def get_camera_property_int(self, key: str) -> int:
        ...
    def get_camera_rotation(self) -> numpy.ndarray[typing.Literal[4], numpy.dtype[numpy.float32]]:
        ...
    def get_content_scale(self) -> float:
        ...
    def get_picture(self, name: str) -> numpy.ndarray[typing.Any, numpy.dtype[typing.Any]]:
        ...
    def get_picture_pixel(self, name: str, x: int, y: int) -> numpy.ndarray[typing.Any, numpy.dtype[typing.Any]]:
        ...
    def get_picture_size(self, name: str) -> typing.Annotated[list[int], pybind11_stubgen.typing_ext.FixedSize(2)]:
        ...
    def hide(self) -> None:
        ...
    def key_down(self, key: str) -> bool:
        ...
    def key_press(self, key: str) -> bool:
        ...
    def mouse_click(self, key: int) -> bool:
        ...
    def mouse_down(self, key: int) -> bool:
        ...
    def render(self, target_name: str, ui_windows: list[sapien.pysapien.internal_renderer.UIWidget] = []) -> None:
        ...
    def resize(self, width: int, height: int) -> None:
        ...
    def set_camera_orthographic_parameters(self, near: float, far: float, top: float) -> None:
        ...
    def set_camera_parameters(self, near: float, far: float, fovy: float) -> None:
        ...
    def set_camera_pose(self, pose: sapien.pysapien.Pose) -> None:
        ...
    def set_camera_position(self, position: numpy.ndarray[typing.Literal[3], numpy.dtype[numpy.float32]] | list[float] | tuple) -> None:
        ...
    @typing.overload
    def set_camera_property(self, key: str, value: int) -> None:
        ...
    @typing.overload
    def set_camera_property(self, key: str, value: float) -> None:
        ...
    def set_camera_rotation(self, quat: numpy.ndarray[typing.Literal[4], numpy.dtype[numpy.float32]] | list[float] | tuple) -> None:
        ...
    def set_camera_texture(self, name: str, texture: RenderTexture2D) -> None:
        ...
    def set_camera_texture_array(self, name: str, textures: list[RenderTexture2D]) -> None:
        ...
    def set_content_scale(self, scale: float) -> None:
        ...
    def set_drop_callback(self, callback: typing.Callable[[list[str]], None]) -> None:
        ...
    def set_focus_callback(self, callback: typing.Callable[[int], None]) -> None:
        ...
    def set_intrinsic_parameters(self, near: float, far: float, fx: float, fy: float, cx: float, cy: float, skew: float) -> None:
        ...
    def set_scene(self, scene: sapien.pysapien.Scene) -> None:
        ...
    def set_scenes(self, scenes: list[sapien.pysapien.Scene]) -> None:
        ...
    def configure_physx_gpu_rendering(self, physx_system: sapien.pysapien.physx.PhysxGpuSystem, transport: typing.Literal['auto', 'direct', 'staged', 'cpu-debug'] = 'auto') -> None:
        ...
    def get_physx_gpu_pose(self, pose_index: int) -> sapien.pysapien.Pose | None:
        ...
    def set_shader_dir(self, shader_dir: str) -> None:
        ...
    def show(self) -> None:
        ...
    def unset_drop_callback(self) -> None:
        ...
    def unset_focus_callback(self) -> None:
        ...
    def update_render(self) -> None:
        """
        Equivalent to calling the update_render function for all added scene
        """
    @property
    def _internal_renderer(self) -> sapien.pysapien.internal_renderer.Renderer:
        ...
    @property
    def _internal_scene(self) -> sapien.pysapien.internal_renderer.Scene:
        ...
    @property
    def alt(self) -> bool:
        ...
    @property
    def camera_mode(self) -> typing.Literal['perspective', 'orthographic']:
        ...
    @property
    def ctrl(self) -> bool:
        ...
    @property
    def display_picture_names(self) -> list[str]:
        """
        Names for available display targets that can be displayed in the render function
        """
    @property
    def far(self) -> float:
        ...
    @property
    def fovy(self) -> float:
        ...
    @property
    def fps(self) -> float:
        ...
    @property
    def mouse_delta(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(2)]:
        ...
    @property
    def mouse_position(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(2)]:
        ...
    @property
    def mouse_wheel_delta(self) -> typing.Annotated[list[float], pybind11_stubgen.typing_ext.FixedSize(2)]:
        ...
    @property
    def near(self) -> float:
        ...
    @property
    def physx_gpu_system(self) -> sapien.pysapien.physx.PhysxGpuSystem | None:
        ...
    @property
    def pose_transport(self) -> str:
        ...
    @property
    def pose_transfer_bytes(self) -> int:
        ...
    @property
    def ortho_top(self) -> float:
        ...
    @property
    def shift(self) -> bool:
        ...
    @property
    def should_close(self) -> bool:
        ...
    @property
    def size(self) -> typing.Annotated[list[int], pybind11_stubgen.typing_ext.FixedSize(2)]:
        ...
    @property
    def super(self) -> bool:
        ...
class SapienRenderer:
    def __init__(self, device: sapien.pysapien.Device | None = None) -> None:
        ...
    @property
    def _internal_context(self) -> sapien.pysapien.internal_renderer.Context:
        ...
def _force_vr_shutdown() -> None:
    """
    SteamVR will be permanently broken (even across processes) when the process is killed without shutting down VR. This function is used to force shutting down VR when you know SAPIEN will be killed without a clean shutdown.
    """
def _internal_set_shader_search_path(path: str) -> None:
    ...
def clear_cache(models: bool = True, images: bool = True, shaders: bool = False) -> None:
    ...
def enable_vr() -> None:
    """
    Enable VR via Steam. Must be called before creating RenderSystem or sapien Scene.
    """
def get_camera_shader_dir() -> str:
    ...
def get_device_summary() -> str:
    ...
def get_imgui_ini_filename() -> str:
    ...
def get_msaa() -> int:
    ...
def get_ray_tracing_denoiser() -> typing.Literal['none', 'oidn', 'optix']:
    ...
def get_ray_tracing_dof_aperture() -> float:
    ...
def get_ray_tracing_dof_plane() -> float:
    ...
def get_ray_tracing_path_depth() -> int:
    ...
def get_ray_tracing_samples_per_pixel() -> int:
    ...
def get_viewer_shader_dir() -> str:
    ...
def get_vr_action_manifest_filename() -> str:
    ...
def get_vr_enabled() -> bool:
    ...
def load_scene(filename: str, apply_scale: bool = True) -> RenderSceneLoaderNode:
    ...
def set_camera_shader_dir(dir: str) -> None:
    ...
def set_global_config(max_num_materials: int = 128, max_num_textures: int = 512, default_mipmap_levels: int = 1, do_not_load_texture: bool = False) -> None:
    """
    Sets global properties for SAPIEN renderer. This function should only be called before creating any renderer-related objects.
    """
def set_imgui_ini_filename(filename: str) -> None:
    ...
def set_log_level(level: str) -> None:
    ...
def set_light_colors(lights: list[RenderLightComponent], colors: numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]]) -> None:
    """
    Batch-set light colors, primarily for per-environment lighting randomization. Colors are
    finite non-negative [r, g, b] rows; values above 1 are valid HDR intensities.

    The whole batch is validated first and a failed call never leaves it partially applied.
    Colors stay CPU real-time in every pose mode; they take effect at the next update_render()
    (or immediately for ordinary CPU rendering).

    Args:
        lights: list of RenderLightComponent
        colors: [N, 3] array of colors, one row per light
    """
def set_light_directions(lights: list[RenderLightComponent], directions: numpy.ndarray[tuple[M, typing.Literal[3]], numpy.dtype[numpy.float32]]) -> None:
    """
    Batch-point directional/spot/textured lights along directions, primarily for per-environment
    lighting randomization. SAPIEN lights shine along +x of their pose; each light's local
    position is kept. Point and parallelogram lights are rejected.

    The whole batch is validated first and a failed call never leaves it partially applied.
    Lights sealed by a RenderSystemGroup must use pose mode 'cpu'; the directions take effect at
    the next update_render().

    Args:
        lights: list of RenderDirectionalLightComponent / RenderSpotLightComponent /
            RenderTexturedLightComponent
        directions: [N, 3] array of finite non-zero directions, one row per light
    """
def set_light_poses(lights: list[RenderLightComponent], poses: numpy.ndarray[tuple[M, typing.Literal[7]], numpy.dtype[numpy.float32]]) -> None:
    """
    Batch-set the local pose of lights, primarily for per-environment lighting randomization.
    Each row of poses is [x, y, z, qw, qx, qy, qz] (the world pose when the owning entity pose is
    identity); quaternions are normalized before being applied.

    The whole batch is validated first and a failed call never leaves it partially applied.
    Lights sealed by a RenderSystemGroup must use pose mode 'cpu'; the poses take effect at the
    next update_render().

    Args:
        lights: list of RenderLightComponent
        poses: [N, 7] array of poses, one [x, y, z, qw, qx, qy, qz] row per light
    """
def set_msaa(msaa: int) -> None:
    ...
def set_picture_format(name: str, format: str) -> None:
    ...
def set_ray_tracing_denoiser(name: typing.Literal['none', 'oidn', 'optix']) -> None:
    ...
def set_ray_tracing_dof_aperture(radius: float) -> None:
    ...
def set_ray_tracing_dof_plane(depth: float) -> None:
    ...
def set_ray_tracing_path_depth(depth: int) -> None:
    ...
def set_ray_tracing_samples_per_pixel(spp: int) -> None:
    ...
def set_viewer_shader_dir(dir: str) -> None:
    ...
def set_vr_action_manifest_filename(filename: str) -> None:
    ...
